Homework 4
GeViN-Gl/courses-app pull request #5
Opened 2023-04-06 14:21 UTC by GeViN-Gl

2023-04-07 11:04 UTC, EpamFanAnton requested changes

2023-04-07 11:04 UTC, EpamFanAnton commented on src/components/CourseForm/CourseForm.tsx
This file looks so complicated because you decided to combine create course and update course. 
Your handlers are extremely robust and complicated, I can't read them ones again. 

You can use something like boolean `isUpdate` it will be true if param is `update` instead of `mode` with string value.
I think if you make your "update" or "add" decision as I suggested higher you will be able to refactor them a little.

2023-04-07 11:04 UTC, EpamFanAnton commented on src/helpers/dataFetchers.ts
Here you are overcomplicating things ones again. Instead of creating separate functions with distinguish names you are  creating this function that is really hard to read, especially when this function is used.

2023-04-09 17:42 UTC, GeViN-Gl commented on src/helpers/dataFetchers.ts
I rewrote it completely. Now it's just a new file.
One action - one function, everything is pure.

2023-04-09 17:52 UTC, GeViN-Gl commented on src/components/CourseForm/CourseForm.tsx
It wasn't me who decided to combine Update and Add behavior.
That's the task.
![image](https://user-images.githubusercontent.com/90048259/230788250-cc29e990-3cfa-489c-9c21-7d957e32fcc0.png)
But I've rewrite it a lot, thrown out the extra local state.
I converted 4 handlers into one.
It simply checks isUpdate twice, before requesting the API and before changing the Store

isUpdate is now just a props

2023-04-11 09:49 UTC, EpamFanAnton approved these changes
25

2023-04-11 09:50 UTC, merged